import {
  INodeDocAduanera,
  INodeGuiasIdent,
  INodeMerc,
  INodeMercancias,
  IObjectNodeDocAduanera,
  IObjectNodeGuiasIdent,
  IObjectNodeMerc,
  IObjectNodeMercancias,
} from "../interfaces/ICartaPorte";

export const merc_att_keys: { entrada: keyof INodeMercancias; salida: keyof IObjectNodeMercancias }[] = [
  { entrada: "cargoPorTasacion", salida: "@_CargoPorTasacion" },
  { entrada: "logisticaInversaRecoleccionDevolucion", salida: "@_LogisticaInversaRecoleccionDevolucion" },
  { entrada: "numTotalMercancias", salida: "@_NumTotalMercancias" },
  { entrada: "pesoBrutoTotal", salida: "@_PesoBrutoTotal" },
  { entrada: "pesoNetoTotal", salida: "@_PesoNetoTotal" },
  { entrada: "unidadPeso", salida: "@_UnidadPeso" },
];
export const mercancia_keys: { entrada: keyof INodeMerc; salida: keyof IObjectNodeMerc }[] = [
  { entrada: "bienesTransp", salida: "@_BienesTransp" },
  { entrada: "descripcion", salida: "@_Descripcion" },
  { entrada: "cantidad", salida: "@_Cantidad" },
  { entrada: "claveUnidad", salida: "@_ClaveUnidad" },
  { entrada: "pesoEnKg", salida: "@_PesoEnKg" },
  { entrada: "claveStcc", salida: "@_ClaveSTCC" },
  { entrada: "unidad", salida: "@_Unidad" },
  { entrada: "dimensiones", salida: "@_Dimensiones" },
  { entrada: "materialPeligroso", salida: "@_MaterialPeligroso" },
  { entrada: "cveMaterialPeligroso", salida: "@_CveMaterialPeligroso" },
  { entrada: "embalaje", salida: "@_Embalaje" },
  { entrada: "descripEmbalaje", salida: "@_DescripEmbalaje" },
  { entrada: "sectorCofepris", salida: "@_SectorCOFEPRIS" },
  { entrada: "nombreIngredienteActivo", salida: "@_NombreIngredienteActivo" },
  { entrada: "nomQuimico", salida: "@_NomQuimico" },
  { entrada: "denominacionGenericaProd", salida: "@_DenominacionGenericaProd" },
  { entrada: "denominacionDistintivaProd", salida: "@_DenominacionDistintivaProd" },
  { entrada: "fabricante", salida: "@_Fabricante" },
  { entrada: "fechaCaducidad", salida: "@_FechaCaducidad" },
  { entrada: "loteMedicamento", salida: "@_LoteMedicamento" },
  { entrada: "formaFarmaceutica", salida: "@_FormaFarmaceutica" },
  { entrada: "condicionesEspTransp", salida: "@_CondicionesEspTransp" },
  { entrada: "registroSanitarioFolioAutorizacion", salida: "@_RegistroSanitarioFolioAutorizacion" },
  { entrada: "permisoImportacion", salida: "@_PermisoImportacion" },
  { entrada: "folioImpoVucem", salida: "@_FolioImpoVUCEM" },
  { entrada: "numCas", salida: "@_NumCAS" },
  { entrada: "razonSocialEmpImp", salida: "@_RazonSocialEmpImp" },
  { entrada: "numRegSanPlagCofepris", salida: "@_NumRegSanPlagCOFEPRIS" },
  { entrada: "datosFabricante", salida: "@_DatosFabricante" },
  { entrada: "datosFormulador", salida: "@_DatosFormulador" },
  { entrada: "datosMaquilador", salida: "@_DatosMaquilador" },
  { entrada: "usoAutorizado", salida: "@_UsoAutorizado" },
  { entrada: "valorMercancia", salida: "@_ValorMercancia" },
  { entrada: "moneda", salida: "@_Moneda" },
  { entrada: "fraccionArancelaria", salida: "@_FraccionArancelaria" },
  { entrada: "uuidComercioExt", salida: "@_UUIDComercioExt" },
  { entrada: "tipoMateria", salida: "@_TipoMateria" },
  { entrada: "descripcionMateria", salida: "@_DescripcionMateria" },
];
export const merc_doc_aduanera: { entrada: keyof INodeDocAduanera; salida: keyof IObjectNodeDocAduanera }[] = [
  { entrada: "identDocAduanero", salida: "@_IdentDocAduanero" },
  { entrada: "numPedimento", salida: "@_NumPedimento" },
  { entrada: "rfcImpo", salida: "@_RFCImpo" },
  { entrada: "tipoDocumento", salida: "@_TipoDocumento" },
];
export const merc_guias_ident: { entrada: keyof INodeGuiasIdent; salida: keyof IObjectNodeGuiasIdent }[] = [
  { entrada: "descripGuiaIdentificacion", salida: "@_DescripGuiaIdentificacion" },
  { entrada: "numeroGuiaIdentificacion", salida: "@_NumeroGuiaIdentificacion" },
  { entrada: "pesoGuiaIdentificacion", salida: "@_PesoGuiaIdentificacion" },
];
